// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// getdns_test
void getdns_test();
RcppExport SEXP _getdns_getdns_test() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    getdns_test();
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_getdns_getdns_test", (DL_FUNC) &_getdns_getdns_test, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_getdns(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
